- entrant:
    pic:
      - Totally Bald
      - Goatee
      - Thick Glasses
      - Slim Figure
    firstname: Ayoub
    lastname: Jarvinen
    sex: M
    date_of_birth: 22/11/1956
    height: 1.86
    weight: 55
    country: antegria
    city: St. Marmero
    purpose: Transit
    bribe: 5
    illegal: true
  passport:
    pic:
      - Totally Bald
      - Goatee
      - Thick Glasses
      - Slim Figure
    firstname: Ayoub
    lastname: Jarvinen
    passport_number: JY9757ACX1
    moa_stamp: AG
    sex: F
    date_of_birth: 22/11/1956
    country: antegria
    issuing_city: St. Marmero
    expiration_date: 28/4/1984
  accesspermit:
    firstname: Ayoub
    lastname: Jarvinen
    moa_stamp: AA
    nationality: unitedfederation
    passport_number: JY9757ACX1
    purpose: Transit
    duration: 13
    height: 1.86
    weight: 55
    expiration_date: 13/3/1984
    physical_appearance: Goatee
- entrant:
    pic:
      - Unkempt Curly Hair
      - Clean Shaven
      - Glasses
      - None
    firstname: Flurin
    lastname: Khan
    sex: M
    date_of_birth: 10/5/1931
    height: 1.99
    weight: 77
    country: kolechia
    city: West Grestin
    purpose: Immigrate
    bribe: 0
    illegal: false
  passport:
    pic:
      - Unkempt Curly Hair
      - Clean Shaven
      - Glasses
      - None
    firstname: Flurin
    lastname: Khan
    passport_number: LGQKF3PKE5
    moa_stamp: AA
    sex: M
    date_of_birth: 10/5/1931
    country: kolechia
    issuing_city: West Grestin
    expiration_date: 14/7/1984
  accesspermit:
    firstname: Flurin
    lastname: Khan
    moa_stamp: AB
    nationality: kolechia
    passport_number: LGQKF3PKE5
    purpose: Immigrate
    duration: 30
    height: 1.99
    weight: 77
    expiration_date: 20/6/1983
    physical_appearance: Clean Shaven
